apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-traefik-server
rules:
- apiGroups:
  - "traefik.containo.us"
  resources:
  - traefikservices
  #- endpoints
  #- pods
  verbs:
  - get
  - list
  - watch
  - update
