apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-traefik-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-traefik-server
subjects:
- kind: ServiceAccount
  name: custom-traefik-server
  namespace: default
